version: '3'
services:
  plex:
      image: plexinc/pms-docker:latest
      container_name: dockerplex
      restart: unless-stopped
      environment:
        - TZ=America/Chicago
        - PLEX_CLAIM=claim-ywTiZeitBUuzey18Whs1
      network_mode: host
      volumes:
      - .:/config
      - .:/transcode
      - .:/data
      ## this assumes the volume used is called "plex"
volumes:
    plex:
