version: '23'
services:
  plex:
      image: plexinc/pms-docker:latest
      container_name: dockerplex
      restart: unless-stopped
      environment:
        - TZ=America/Chicago
      network_mode: host
      volumes:
      - .:/config
      - .:/transcode
      - .:/data
volumes:
    plex:
