services:
  plex:
    image: plexinc/pms-docker
    container_name: Plex
    network_mode: bridge
    environment:
      - VERSION=docker
    restart: unless-stopped
    volumes:
      - "test-movies:/media/"
      - "test-movies:/transcode"
      - "test-movies:/data"
volumes:
  test-movies:
    external: true