version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-ywTiZeitBUuzey18Whs1
    network_mode: host
    volumes:
      - test-movies:/config
      - test-movies:/transcode
      - test-movies:/data
